### ISSUE TITLE
demo links are broken

### ISSUE THREAD

**Issue by philderbeast** [elierotenberg/react-styling-demo#1]
The demo links on the page https://github.com/elierotenberg/react-styling-demo are broken. For example ...

http://elie.rotenberg.io/react-styling-demo/dist/SimpleAnimation.html

**Comment by elierotenberg** [comment]
Thanks for the ticket, I have indeed modified the file structure of my homepage and thus the demos were removed.
I've added them back at a new url and updated the README.md file accordingly.
